### ISSUE TITLE
Emerge Broken (AMD64)

### ISSUE THREAD

**Issue by gitgud-software** [damex/deadbeef-overlay#10]
The dependencies installed normally, but deadbeef's ebuild isn't working on my laptop. The attached documents are the build.log and the info page for the attempted install.

[deadbeef-build-log.txt](https://github.com/damex/deadbeef-overlay/files/178870/deadbeef-build-log.txt)
[deadbeef-install.txt](https://github.com/damex/deadbeef-overlay/files/178871/deadbeef-install.txt)

**Comment by damex** [comment]
thank you. merged changes. it should be fixed from now on.
