### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by dave-kennedy** [damex/deadbeef-overlay#11]
Just curious, why is this an overlay and not part of the portage tree?

**Comment by damex** [comment]
- licensing issues. people tend to not update licenses (and there is a huge list of them) in time which cause issues.
- dependency issues. people's insanity take over and they want everything to be built against libraries included at the gentoo tree. there is some heavy modified libs inside deadbeef tree. not going to happen.
- maintaining issues. no one out there is interested in maintaining that deadbeef.
- whatever it is

have you seen a list of requirement to join gentoo? hurr durr

**Comment by dave-kennedy** [comment]
Yeah, it's pretty hard to get contributions into the portal tree. Good reasons. Thanks!
