### ISSUE TITLE
configure doesn't find ffmpeg codecs

### ISSUE THREAD

**Issue by fcll** [damex/deadbeef-overlay#14]
I'm having a problem with the ffmpeg plugin. I've enabled the ffmpeg USE in media-sound/deadbeef and I see that --enable-ffmpeg is passed but I get `ffmpeg: no - ffmpeg codecs` for the plugin summary and the plugin doesn't get build.
`media-sound/deadbeef-0.7.2-r1::deadbeef-overlay was built with the following:
USE="alsa cover ffmpeg flac gtk2 hotkeys mad mp3 sndfile vorbis -aac -adplug -alac -cdda -cdparanoia -converter -cover-imlib2 -cover-network -curl -dts -dumb -equalizer -gme -gtk3 -lastfm -libav -libnotify -libsamplerate -m3u -mac -midi -mms -mono2stereo -mpg123 -musepack -nls -nullout -oss -playlist-browser -psf -pulseaudio -sc68 -shell-exec -shn -sid -tta -unity -vtx -wavpack -wma -zip" ABI_X86="(64)" LINGUAS="-be -bg -bn -ca -cs -da -de -el -en_GB -es -et -eu -fa -fi -fr -gl -he -hr -hu -id -it -ja -kk -km -lg -lt -nl -pl -pt -pt_BR -ro -ru -si_LK -sk -sl -sr -sr@latin -sv -te -tr -ug -uk -vi -zh_CN -zh_TW`

`media-video/ffmpeg-3.3.3::gentoo was built with the following:
USE="X alsa bzip2 encode gpl hardcoded-tables iconv libass mp3 network opengl openssl opus postproc threads truetype vdpau vorbis x264 xcb xvid zlib (-altivec) -amr -amrenc -bluray -bs2b -cdio -celt -chromaprint -cpudetection -debug -doc -fdk -flite -fontconfig -frei0r -fribidi -gcrypt -gme -gmp -gnutls -gsm -iec61883 -ieee1394 -jack -jpeg2k -kvazaar -ladspa -libcaca -libilbc -librtmp -libsoxr -libv4l -lzma (-mipsdspr1) (-mipsdspr2) (-mipsfpu) (-mmal) -modplug -nvenc -openal -openh264 -oss -pic -pulseaudio -rubberband -samba -schroedinger -sdl -snappy -sofalizer -speex -ssh -static-libs -test -theora -twolame -v4l -vaapi -vpx -wavpack -webp -x265 -zeromq -zimg -zvbi" ABI_X86="(64) -32 (-x32)" CPU_FLAGS_X86="aes avx avx2 fma3 mmx mmxext sse sse2 sse3 sse4_1 sse4_2 ssse3 -3dnow -3dnowext -fma4 -xop" FFTOOLS="aviocat cws2fws ffescape ffeval ffhash fourcc2pixfmt graph2dot ismindex pktdumper qt-faststart sidxindex trasher"`

**Comment by damex** [comment]
not sure if i can reproduce this one... can i see the build log (with --enable-ffmpeg)?

**Comment by damex** [comment]
i just tried last gentoo stable from vagrant and i get the same issue as above.

need some investigation - both 0.7.2 and 9999 ebuilds are affected.

**Comment by damex** [comment]
just fixed and committed a fix.

https://github.com/damex/deadbeef-overlay/commit/2d741c73a7c52746d25ec8cfb9e65cf2b5a28ee3

issue is solved for now.

thank you for reporting.
