### ISSUE TITLE
deadbeef-fb version bump for compatibility with gtk+3.22

### ISSUE THREAD

**Issue by ngleb** [damex/deadbeef-overlay#18]
git tree contains important fixes to fix building the plugin with gtk+3.22:
https://gitlab.com/zykure/deadbeef-fb/commit/47bc3fe0fe151dfbb75f90f9e4d5e9a7affd280a

Could you please update the snapshot?

**Comment by damex** [comment]
just did a bump.
repoman tests are passing successfully and deadbeef-fb seem to build and work just fine.

i will close this issue for now :)
