### ISSUE TITLE
problems with decoding encrypted (icecast) mp3 webstreams

### ISSUE THREAD

**Issue by stefson** [damex/deadbeef-overlay#19]
I opened an issue upstream about this, with all informations you may want to know : https://github.com/DeaDBeeF-Player/deadbeef/issues/1982

If you can reproduce on your end, can you please disable libmad via the ebuild for mpg123 instead? 

Thank you

**Comment by stefson** [comment]
You ever ran into this on your machine? You can take stream urls from the issue https://github.com/DeaDBeeF-Player/deadbeef/issues/1982

**Comment by stefson** [comment]
@RazrFalcon you ever ran into this?

**Comment by damex** [comment]
Let me try to check that issue, i ain’t using streaming now.

Should that be fine to have option to enable either libmad or mpg123?

**Comment by stefson** [comment]
it's been discussed here: https://github.com/DeaDBeeF-Player/deadbeef/issues/1982

I switched to mpg123 in the meantime, but it doesn't really matter for the issue. Still happens once in a while - stream stops and another one is shuffled in. It doesn't happen with the non encrypted streams from the same station, but I'd rather go with the encrypted ones. The static builds the maintainer offers (links in the before linked issue) don't work at all with streaming. Current live ebuild behaves just like 0.7.2 - if you got an idea how to debug this properly?

**Comment by damex** [comment]
please check if it is still reproducible with 1.8.0 version

**Comment by stefson** [comment]
Thanks for pinging, unfortunatly I have to say that the 1.8.0 release is pretty broken to me. The gui is not always repsonsive, but it doesn't throw out anything useable in gdb. There are segfaults in libglib-2.0 in dmesg to be found, but that's not telling me much. How is your experience with it?

**Comment by damex** [comment]
thanks for feedback.

I just tried running it on a fresh gentoo stable (amd64) and it seem to be functioning well without segfaults or stutters/unresponsive gui.

could you please provide more details about your setup?

**Comment by stefson** [comment]
emerge deadbeef-1.8.0 with USE="aac adplug alac alsa cdda converter cover cover-imlib2 curl ffmpeg flac gtk2 hotkeys lastfm libsamplerate m3u mad mms mp3 musepack nls shn sndfile tta vorbis wavpack wma zip -cdparanoia -cover-network -dts -dumb -equalizer -gme -gtk3 -libav -libnotify -mac -midi -mono2stereo -mpg123 -nullout -opus -oss -playlist-browser -psf -pulseaudio -sc68 -shell-exec -sid -unity -vtx" 

moved profile to backup, so starting with a fresh one. Tune in bbc live stream: http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio5live_mf_p 

result: some data is downloaded, but nothing happens and the gui freezes. Has to be killed via taskmanager. Dmesg is clean and pushing it through debugger doesn't help, as there's no real crash.

**Comment by damex** [comment]
> emerge deadbeef-1.8.0 with USE="aac adplug alac alsa cdda converter cover cover-imlib2 curl ffmpeg flac gtk2 hotkeys lastfm libsamplerate m3u mad mms mp3 musepack nls shn sndfile tta vorbis wavpack wma zip -cdparanoia -cover-network -dts -dumb -equalizer -gme -gtk3 -libav -libnotify -mac -midi -mono2stereo -mpg123 -nullout -opus -oss -playlist-browser -psf -pulseaudio -sc68 -shell-exec -sid -unity -vtx"
> 
> moved profile to backup, so starting with a fresh one. Tune in bbc live stream: http://bbcmedia.ic.llnwd.net/stream/bbcmedia_radio5live_mf_p
> 
> result: some data is downloaded, but nothing happens and the gui freezes. Has to be killed via taskmanager. Dmesg is clean and pushing it through debugger doesn't help, as there's no real crash.

can you please try disabling gtk2 and use gtk3 only? to see if it helps.

**Comment by stefson** [comment]
No, been there, it doesn't make a difference. By the way, the patches don't apply anymore to your live ebuild :-)

**Comment by damex** [comment]
> No, been there, it doesn't make a difference. By the way, the patches don't apply anymore to your live ebuild :-)

can you provide a full log of deadbeef run? (just run it from CLI and it will output everything to stdout)
I wonder if you have any 3rd party plugins installed or if there is other errors.

**Comment by stefson** [comment]
no, there's nothing as a third party plugin involved: 

```
starting deadbeef 1.8.0
server_start
searching for GUI plugins in /home/user/.local/lib64/deadbeef
searching for GUI plugins in /home/user/.local/lib/deadbeef
searching for GUI plugins in /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 63 files
found gui plugin ddb_gui_GTK2.so
added GTK2 gui plugin
found gui plugin ddb_gui_GTK3.so
added GTK3 gui plugin
load gui plugin
checking GUI plugin: GTK2
checking GUI plugin: GTK3
found selected GUI plugin: GTK3
loading plugin /usr/lib64/deadbeef/ddb_gui_GTK3.so
loading plugins from /home/tim/.local/lib64/deadbeef
loading plugins from /home/tim/.local/lib/deadbeef
loading plugins from /usr/lib64/deadbeef
load_plugin_dir /usr/lib64/deadbeef: scandir found 63 files
loading plugin /usr/lib64/deadbeef/aac.so
loading plugin /usr/lib64/deadbeef/adplug.so
loading plugin /usr/lib64/deadbeef/alac.so
loading plugin /usr/lib64/deadbeef/alsa.so
loading plugin /usr/lib64/deadbeef/artwork.so
loading plugin /usr/lib64/deadbeef/cdda.so
loading plugin /usr/lib64/deadbeef/converter.so
loading plugin /usr/lib64/deadbeef/converter_gtk2.so
loading plugin /usr/lib64/deadbeef/converter_gtk3.so
loading plugin /usr/lib64/deadbeef/ddb_shn.so
loading plugin /usr/lib64/deadbeef/dsp_libsrc.so
loading plugin /usr/lib64/deadbeef/ffmpeg.so
loading plugin /usr/lib64/deadbeef/flac.so
loading plugin /usr/lib64/deadbeef/hotkeys.so
loading plugin /usr/lib64/deadbeef/lastfm.so
loading plugin /usr/lib64/deadbeef/m3u.so
loading plugin /usr/lib64/deadbeef/mms.so
loading plugin /usr/lib64/deadbeef/mp3.so
loading plugin /usr/lib64/deadbeef/musepack.so
loading plugin /usr/lib64/deadbeef/rg_scanner.so
loading plugin /usr/lib64/deadbeef/shellexec.so
loading plugin /usr/lib64/deadbeef/sndfile.so
loading plugin /usr/lib64/deadbeef/tta.so
loading plugin /usr/lib64/deadbeef/vfs_curl.so
loading plugin /usr/lib64/deadbeef/vfs_zip.so
loading plugin /usr/lib64/deadbeef/vorbis.so
loading plugin /usr/lib64/deadbeef/wavpack.so
loading plugin /usr/lib64/deadbeef/wma.so
starting plugin GTK3 user interface
starting plugin AAC player
starting plugin Adplug player
starting plugin ALAC player
starting plugin ALSA output plugin
starting plugin Album Artwork
starting plugin Audio CD player
starting plugin Converter
starting plugin Converter GTK2 UI
starting plugin Converter GTK3 UI
starting plugin Shorten player
starting plugin Resampler (Secret Rabbit Code)
starting plugin FLAC decoder
starting plugin Hotkey manager
starting plugin last.fm scrobbler
starting plugin M3U and PLS support
starting plugin mms vfs
starting plugin MP3 player
starting plugin MusePack decoder
starting plugin ReplayGain Scanner
starting plugin Shell commands
starting plugin WAV/PCM player
starting plugin tta decoder
starting plugin cURL vfs
starting plugin ZIP vfs
starting plugin Ogg Vorbis decoder
starting plugin WavPack decoder
starting plugin WMA player
starting plugin stdio vfs
starting plugin FFMPEG audio player
streamer_set_output
selected output plugin: ALSA output plugin
INFO: from file /home/tim/.config/deadbeef/playlists/0.dbpl
convgui: gtkui plugin not found
plugin Converter GTK2 UI failed to connect to dependencies, deactivated.
resume: track -1 pos -1.000000 playlist -1
gtkui plugin compiled for gtk version: 3.24.4
connecting button tray signals
```

**Comment by damex** [comment]
> By the way, the patches don't apply anymore to your live ebuild :-)

thanks, it should be fixed with https://github.com/damex/deadbeef-overlay/commit/f7ad3fd5537166e8e1b6b02234a7dab98ef52889

**Comment by stefson** [comment]
are you on pulseaudio?

**Comment by damex** [comment]
> are you on pulseaudio?

I tried running both pure also and with pulse on top. no difference for lagging.

could you please create a separate issue about your freezing interface? attach strace output when it happens please.

another question - does this patch (disables ssl verification) helps to solve the issue playing encrypted ice cast mp3 streams?
https://github.com/DeaDBeeF-Player/deadbeef/issues/1982#issuecomment-409166974

**Comment by stefson** [comment]
I'll do so; in the meantime I pinned the problems with 1.8.0 down to pulseaudio not being emerged on my end. This doesn't mean something is broken on deadbeefs end, more effort from me is needed to find the real cause. 

regarding the patch, I'm not interested into picking it up because it makes the connection insecure.

**Comment by stefson** [comment]
fixed in git via https://github.com/DeaDBeeF-Player/deadbeef/issues/2192
