### ISSUE TITLE
media-plugins/deadbeef-soxr: update for soxr-0.1.3

### ISSUE THREAD

**Issue by nick87720z** [damex/deadbeef-overlay#24]
This issue should go to deadbeef-soxr repo, but by mistake i made it in overlay's repo.
Reported there: https://github.com/silentlexx/deadbeef_soxr/issues/4

Edit: fixed in upstream by https://github.com/silentlexx/deadbeef_soxr/commit/103341b7388d38110181494bb9763daa9dafa63e

P.S. sorry for somewhat uncertain issue name, now updated.

**Comment by damex** [comment]
necessary changes got merged as a part of

https://github.com/damex/deadbeef-overlay/commit/de9b30d96a1dcd009a0af2ccef056adcb3cd0fc2

should be fine from now on, if not - please open a new issue.

thank you.
