### ISSUE TITLE
deadbeef-9999 gives warning "gnome2_icon_cache_update: command not found"

### ISSUE THREAD

**Issue by stefson** [damex/deadbeef-overlay#31]
not sure why this fails, and if it is related to the problems I experience?

[deadbeef-build.log.gz](https://github.com/damex/deadbeef-overlay/files/3144391/deadbeef-build.log.gz)

**Comment by damex** [comment]
hi, I just updated deadbeef Ebuilds.

according to devmanuals - gnome2_icon_cache_update is deprecated.
I replaced it by xdg_icon_cache_update from xdc-utils eclass (official recommendation).

please check it again and report back. thank you.

**Comment by stefson** [comment]
This looks good to me for 0.7.2 and 1.8.0, can't tell for the live ebuild as one patch fails: 

```
>>> Preparing source in /var/tmp/portage/media-sound/deadbeef-9999/work/deadbeef-9999 ...
 * Applying deadbeef-9999-remove-ru-help-translation.patch ...                                                                                                                   [ ok ]
removed '/var/tmp/portage/media-sound/deadbeef-9999/work/deadbeef-9999/translation/help.ru.txt'
 * Applying deadbeef-9999-remove-ru-help-translation.patch ...
1 out of 1 hunk FAILED -- saving rejects to file Makefile.am.rej                                                                                                                 [ !! ]
 * ERROR: media-sound/deadbeef-9999::deadbeef-overlay failed (prepare phase):
```

**Comment by damex** [comment]
> This looks good to me for 0.7.2 and 1.8.0, can't tell for the live ebuild as one patch fails:
> 
> ```
> >>> Preparing source in /var/tmp/portage/media-sound/deadbeef-9999/work/deadbeef-9999 ...
>  * Applying deadbeef-9999-remove-ru-help-translation.patch ...                                                                                                                   [ ok ]
> removed '/var/tmp/portage/media-sound/deadbeef-9999/work/deadbeef-9999/translation/help.ru.txt'
>  * Applying deadbeef-9999-remove-ru-help-translation.patch ...
> 1 out of 1 hunk FAILED -- saving rejects to file Makefile.am.rej                                                                                                                 [ !! ]
>  * ERROR: media-sound/deadbeef-9999::deadbeef-overlay failed (prepare phase):
> ```

thanks, just pushed fix for live/9999 ebuild. it would fix location for git repository (changed officially) and I also cleaned up leftovers of previous step of ru patch removal (left there by mistake, ru patch was applying twice in a row).

please check it again and report back. thank you.

**Comment by stefson** [comment]
it's all fixed, thank you for taking care of it :)
