### ISSUE TITLE
Wrong checksum for deadbeef-1.8.0.tar.bz2

### ISSUE THREAD

**Issue by xyzz** [damex/deadbeef-overlay#34]
Getting a checksum failure when downloading the source archive:

```
!!! Fetched file: deadbeef-1.8.0.tar.bz2 VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      4849778
!!! Expected: 4849549
```

**Comment by damex** [comment]
thank you, should be fixed with https://github.com/damex/deadbeef-overlay/pull/33 since this one is merged.

please test it on your side and report back. thank you.

**Comment by xyzz** [comment]
Thanks, it builds now.
